[package]
name = "experienced-slash"
version = "0.1.0"
edition = "2021"
authors = ["valkyrie_pilot <valk@randomairborne.dev>"]
description = "A slash command handler for experienced"
repository = "https://github.com/randomairborne/experienced"
readme = "README.txt"
license = "MS-PL"
categories = ["games"]
keywords = ["discord-bot", "mee6"]

[dependencies]
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
sqlx = { version = "0.6", features = ["runtime-tokio-rustls", "tls", "mysql", "macros"] }
axum = "0.6.0-rc.2"
serde_json = "1"
ed25519-dalek = "1"
hex = "0.4"
thiserror = "1"
twilight-model = "0.14"
twilight-http = "0.14"
twilight-util = { version = "0.13", features = ["builder"] }
dotenvy = "0.15"
mee6 = "0.0.2"
