[package]
name = "xpd-util"
version = "0.1.0"
edition = "2021"

[dependencies]
twilight-cache-inmemory = { version = "0.16.0", features = ["permission-calculator"] }
twilight-model = "0.16.0"

# error handling
thiserror = "2"
tracing = "0.1"