[package]
name = "xpd-listener"
version = "0.1.0"
edition = "2021"
authors = ["valkyrie_pilot <valk@randomairborne.dev>"]
description = "A websocket listener for experienced"
repository = "https://github.com/randomairborne/experienced"
readme = "README.txt"
license = "MS-PL"
categories = ["games"]
keywords = ["discord-bot", "mee6"]

[dependencies]
twilight-gateway = { version = "0.15", features = ["rustls-native-roots", "twilight-http"], default-features = false }
sqlx = { version = "0.7", features = ["runtime-tokio", "tls-rustls", "postgres", "macros"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros", "signal"] }
redis = { version = "0.23", default-features = false, features = ["aio"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
deadpool-redis = { version = "0.12", features = ["rt_tokio_1"] }
xpd-common = { path = "../xpd-common/", version = "0.0.5" }
twilight-model = "0.15"
twilight-http = "0.15"
serde_json = "1"
dotenvy = "0.15"
thiserror = "1"
rand = "0.8"
mee6 = "0.1"
